class Autogenerated {
  String? status;
  String? token;
  Data? data;

  Autogenerated({this.status, this.token, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    token = json['token'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['token'] = this.token;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  User? user;

  Data({this.user});

  Data.fromJson(Map<String, dynamic> json) {
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    return data;
  }
}

class User {
  String? sId;
  String? name;
  String? email;
  String? role;
  int? iV;
  String? passwordChangedAt;
  String? passwordResetExpires;
  String? passwordResetToken;

  User(
      {this.sId,
      this.name,
      this.email,
      this.role,
      this.iV,
      this.passwordChangedAt,
      this.passwordResetExpires,
      this.passwordResetToken});

  User.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    name = json['name'];
    email = json['email'];
    role = json['role'];
    iV = json['__v'];
    passwordChangedAt = json['passwordChangedAt'];
    passwordResetExpires = json['passwordResetExpires'];
    passwordResetToken = json['passwordResetToken'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['name'] = this.name;
    data['email'] = this.email;
    data['role'] = this.role;
    data['__v'] = this.iV;
    data['passwordChangedAt'] = this.passwordChangedAt;
    data['passwordResetExpires'] = this.passwordResetExpires;
    data['passwordResetToken'] = this.passwordResetToken;
    return data;
  }
}
